// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DialogueController from "./dialogue_controller"
application.register("dialogue", DialogueController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TakeTurnController from "./take_turn_controller"
application.register("take-turn", TakeTurnController)

import TurboFetchController from "./turbo_fetch_controller"
application.register("turbo-fetch", TurboFetchController)

import TurnTimerController from "./turn_timer_controller"
application.register("turn-timer", TurnTimerController)
